-- Create system_settings table for configurable application parameters
CREATE TABLE system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value TEXT,
    setting_type VARCHAR(50) NOT NULL CHECK (setting_type IN ('STRING', 'INTEGER', 'DECIMAL', 'BOOLEAN', 'JSON', 'EMAIL', 'URL', 'PASSWORD', 'ENUM')),
    category VARCHAR(50) NOT NULL CHECK (category IN ('GENERAL', 'EMAIL', 'OCR', 'SECURITY', 'NOTIFICATIONS', 'PERFORMANCE', 'INTEGRATION', 'LOGGING')),
    display_name VARCHAR(200) NOT NULL,
    description TEXT,
    default_value TEXT,
    validation_regex VARCHAR(500),
    min_value DECIMAL,
    max_value DECIMAL,
    allowed_values TEXT,
    is_sensitive BOOLEAN DEFAULT FALSE NOT NULL,
    is_readonly BOOLEAN DEFAULT FALSE NOT NULL,
    requires_restart BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(100)
);

-- Create indexes for performance
CREATE INDEX idx_system_settings_key ON system_settings(setting_key);
CREATE INDEX idx_system_settings_category ON system_settings(category);
CREATE INDEX idx_system_settings_type ON system_settings(setting_type);
CREATE INDEX idx_system_settings_updated_at ON system_settings(updated_at);

-- Add comments for documentation
COMMENT ON TABLE system_settings IS 'Configurable system settings and parameters';
COMMENT ON COLUMN system_settings.setting_key IS 'Unique identifier for the setting (e.g., email.smtp.host)';
COMMENT ON COLUMN system_settings.setting_value IS 'Current value of the setting';
COMMENT ON COLUMN system_settings.setting_type IS 'Data type of the setting value';
COMMENT ON COLUMN system_settings.category IS 'Category grouping for organization';
COMMENT ON COLUMN system_settings.display_name IS 'Human-readable name for the setting';
COMMENT ON COLUMN system_settings.description IS 'Description of what this setting controls';
COMMENT ON COLUMN system_settings.default_value IS 'Default value for the setting';
COMMENT ON COLUMN system_settings.validation_regex IS 'Regular expression for value validation';
COMMENT ON COLUMN system_settings.allowed_values IS 'JSON array of allowed values for enum types';
COMMENT ON COLUMN system_settings.is_sensitive IS 'Whether setting contains sensitive data (passwords, tokens)';
COMMENT ON COLUMN system_settings.is_readonly IS 'Whether setting can be modified through UI';
COMMENT ON COLUMN system_settings.requires_restart IS 'Whether changing this setting requires application restart';
