version: '3.8'

services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: invoice-postgres-dev
    environment:
      POSTGRES_DB: invoice_automation
      POSTGRES_USER: invoice_user
      POSTGRES_PASSWORD: invoice_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis-dev:
    image: redis:7-alpine
    container_name: invoice-redis-dev
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: invoice-mailhog
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP

volumes:
  postgres_data:
