spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:invoice_automation}
    username: ${DB_USERNAME:invoice_user}
    password: ${DB_PASSWORD:invoice_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  mail:
    host: ${EMAIL_HOST:smtp.company.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME:invoice-system@company.com}
    password: ${EMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.company.invoice: INFO
    org.springframework.security: WARN
  file:
    name: /var/log/invoice-automation/application.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

invoice:
  app:
    base-url: ${APP_BASE_URL:https://your-domain.com}
  storage:
    pdf-directory: ${PDF_STORAGE_PATH:/opt/invoice-automation/pdf-storage}
  
  email:
    monitoring:
      enabled: ${EMAIL_MONITORING_ENABLED:true}
      poll-interval: ${EMAIL_POLL_INTERVAL:120000}
      days-to-check: ${EMAIL_DAYS_TO_CHECK:2}
  
  ocr:
    # Tesseract OCR Configuration for Production
    tesseract:
      data-path: ${TESSERACT_DATA_PATH:/usr/share/tesseract-ocr/tessdata}
      language: ${TESSERACT_LANGUAGE:eng}
      dpi: ${TESSERACT_DPI:600}  # Higher DPI for production quality
      timeout-seconds: ${TESSERACT_TIMEOUT:180}  # Longer timeout for production
      page-seg-mode: ${TESSERACT_PSM:3}
      ocr-engine-mode: ${TESSERACT_OEM:3}
    
    # Tika Configuration for Production
    tika:
      max-string-length: ${TIKA_MAX_STRING:200000}  # Higher limit for production
      timeout-seconds: ${TIKA_TIMEOUT:60}  # Longer timeout for production
      preserve-alignment: ${TIKA_PRESERVE_ALIGNMENT:true}
    
    # PDFBox Configuration for Production
    pdfbox:
      sort-by-position: ${PDFBOX_SORT_BY_POSITION:true}
      preserve-spacing: ${PDFBOX_PRESERVE_SPACING:true}
    
    # Coordinator Configuration for Production
    coordinator:
      min-confidence: ${OCR_MIN_CONFIDENCE:0.8}  # Higher threshold for production
      enable-fallback: ${OCR_ENABLE_FALLBACK:true}
      parallel-processing: ${OCR_PARALLEL:true}
      timeout-minutes: ${OCR_TIMEOUT_MINUTES:10}  # Longer timeout for production
  
  security:
    jwt:
      secret: ${JWT_SECRET:}
      expiration: ${JWT_EXPIRATION:86400000}
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:https://invoice.company.com}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
