server:
  port: 8080
  servlet:
    context-path: /invoice-automation

spring:
  application:
    name: invoice-automation-system
  
  profiles:
    active: dev
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
      expiration: 86400000 # 24 hours
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    com.company.invoice: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/invoice-automation.log
  charset:
    console: UTF-8
    file: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

# Application specific configuration
invoice:
  app:
    base-url: ${APP_BASE_URL:http://localhost:8080}
  storage:
    pdf-directory: ${PDF_STORAGE_PATH:./pdf-storage}
    max-file-size: 50MB
  
  ocr:
    # Tesseract OCR Configuration
    tesseract:
      data-path: ${TESSERACT_DATA_PATH:}  # Empty = use embedded tessdata
      language: ${TESSERACT_LANGUAGE:eng}
      dpi: ${TESSERACT_DPI:300}
      timeout-seconds: ${TESSERACT_TIMEOUT:120}
      page-seg-mode: ${TESSERACT_PSM:3}  # Fully automatic page segmentation
      ocr-engine-mode: ${TESSERACT_OEM:3}  # Default, based on what is available
    
    # Tika Configuration
    tika:
      max-string-length: ${TIKA_MAX_STRING:100000}  # 100KB
      timeout-seconds: ${TIKA_TIMEOUT:30}
      preserve-alignment: ${TIKA_PRESERVE_ALIGNMENT:true}  # Preserve text alignment and spacing
    
    # PDFBox Configuration for layout preservation
    pdfbox:
      sort-by-position: ${PDFBOX_SORT_BY_POSITION:true}  # Sort text by spatial position
      preserve-spacing: ${PDFBOX_PRESERVE_SPACING:true}  # Convert multiple spaces to tabs
    
    # Coordinator Configuration
    coordinator:
      min-confidence: ${OCR_MIN_CONFIDENCE:0.7}
      enable-fallback: ${OCR_ENABLE_FALLBACK:true}
      parallel-processing: ${OCR_PARALLEL:true}
      timeout-minutes: ${OCR_TIMEOUT_MINUTES:5}
  
  email:
    monitoring:
      enabled: true
      poll-interval: 120000 # 2 minutes
      days-to-check: 2 # Number of days to look back for unread emails
      
  scheduler:
    # Enable explicit scheduler configuration  
    enabled: true
    heartbeat-interval: 30000 # 30 seconds
  
  security:
    cors:
      allowed-origins: "http://localhost:3000,http://localhost:3001"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

# API Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
